### ISSUE TITLE
Ability to verify navigation on GoBackAync

### ISSUE THREAD

**Issue by mackayn** [Axemasta/Moq.INavigationService#8]
Hi,

I've been using this library as I'm porting tests to Prism. it works really well but I seem unable to verify GoBackAsync, it would be useful as we have a bunch of tests that have conditional checks before navigating back.

**Comment by Axemasta** [comment]
Hi Norm
Glad to hear this has been useful for you! Would you be able to provide a little snippet of the tests you are trying to port?

If memory serves me right I'm not using these extensions in my codebase when working with GoBackAsync. Since it's defined on the interface I'm using the normal Moq verify apis.

**Comment by mackayn** [comment]
I have a base container and I just pass the MockNavigationService into that constructor for the tests

Fails
```
MockNavigationService.VerifyNavigation(n => n.GoBackAsync(), Times.Once);
```
Works fine

```
                  MockNavigationService.VerifyNavigation(
                    s => s.NavigateAsync($"__RemovePage/{NavRoutes.HomePage}", mockNavParams), Times.Once);
```

**Comment by Axemasta** [comment]
Sorry its taken a bit of time to get back to you on this, I've been on my holidays!

I've had a look and verified the issue, there is a bit of a workaround for the timebeing and I can also confirm I will be adding support for this scenario to the `VerifyNavigation` method.

I forget the signature on the interface has no empty nav params, and that is an extension method shwon in your example:
`Task<INavigationResult> GoBackAsync(INavigationParameters parameters);`

You can mock the interface directly if you pass empty parameters to the moq verification:
```csharp
public class GoBackTests
{
	private readonly MockNavigationService navigationService = new();

	[Fact]
	public async Task GoBackAsync_DirectOnInterface_ShouldWork()
	{
		var sut = new MyViewModel(navigationService);

		await sut.GoBack();

		navigationService.Verify(m => m.GoBackAsync(new NavigationParameters()), Times.Once);
	}

	private class MyViewModel(INavigationService navigationService)
	{

		public async Task GoBack()
		{
			await navigationService.GoBackAsync();
		}
	}
}
```

However I will add some support. The reason that the example you gave works fine is the `VerifyNavigation` method is spoofing navigation and trying to build the exact `Uri` that prism is generating.  The code is a bit bodgetastic but its quite amusing that it works in this manor 😂

**Comment by Axemasta** [comment]
Oh and since Prism is now stable, I will be shipping this change in the next version which should be soon!

**Comment by Axemasta** [comment]
New release is published, support for `GoBackAsync` (and the others) has been added. Let me know if you have any more issues 😊

**Comment by mackayn** [comment]
Awesome work dude.

**Comment by mackayn** [comment]
Tested while upgrading the app to fix yet more MAUI issues, works a treat. Thanks again.
